#development:
#    adapter: postgresql
#    database: eventosdb
#    username: ubuntu
#    password: root
#    host: localhost
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000